
CREATE DATABASE XYZ;
USE XYZ;
CREATE TABLE EMPLOYEE_DETAIL(
   ID INT PRIMARY KEY,
   NAME VARCHAR(50),
   SALARY INT
);   
INSERT INTO EMPLOYEE_DETAIL(ID,NAME,SALARY)
VALUES
(1,"ADAM",25000),
(2,"HARDIN",30000),
(3,"MAX",35000);
SELECT * FROM EMPLOYEE_DETAIL;
DROP DATABASE college;
CREATE DATABASE COLLEGE;
USE COLLEGE;
CREATE TABLE STUDENTS(
ROLL_NO INT PRIMARY KEY,
NAME VARCHAR(50),
MARKS INT NOT NULL,
GRADE VARCHAR(1),
CITY VARCHAR(20)
);
INSERT INTO STUDENTS(ROLL_NO,NAME,MARKS,GRADE,CITY)
VALUES
(101,"ADITYA",98,"A","GORAKHPUR"),
(102,"AKHIL",75,"C","ALIGARH"),
(103,"GAURAV",25,"F","LUCKNOW"),
(104,"RAMU",35,"P","MAU"),
(105,"PRANSHU",95,"A","BASTI");
SELECT * FROM STUDENTS;
select name from students;
SELECT * FROM STUDENTS WHERE MARKS>80;
SELECT * FROM STUDENTS WHERE GRADE="A";
SELECT * FROM STUDENTS  ORDER BY MARKS ASC
LIMIT  3;
SELECT * FROM STUDENTS ORDER BY ROLL_NO DESC
LIMIT 5;
SELECT NAME, COUNT(ROLL_NO)
FROM STUDENTS 
GROUP BY NAME;